server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:8070

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackUri: forward:/userServiceFallBack
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE
                backoff:
                  firstBackoff: 1s
                  maxBackoff: 10s
                  factor: 2
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackUri: forward:/departmentServiceFallBack

management:
  tracing:
    sampling:
      probability: 1.0
